server:
  port: 8080
spring:
  datasource:
    tasks:
      jdbc-url: jdbc:postgresql://localhost:5432/eisetasks
      username: eisetasks_admin
      password: eisetasks_admin_pass
      driver-class-name: org.postgresql.Driver