server:
  port: 8080
spring:
  datasource:
    tasks:
      jdbc-url: jdbc:postgresql://localhost:5432/eisetasks
      username: dasha
      password: maya
      driver-class-name: org.postgresql.Driver